---
title: "RNA004_errorfreq"
author: "Laura White"
date: "2023-11-27"
output: html_document
---

```{r}
knitr::opts_chunk$set(echo = F)
library(tidyverse)
library(cowplot)
library(reshape2)
library(here)

here::i_am("rmd/RNA004_errorfreq.Rmd")
```
To compare RNA004 to RNA002 wild type budding yeast tRNA sequencing data, read in our two samples.
```{r}
# little read in function
read_nanoRMS <- function(x) {
  df <- readr::read_csv(x)
  df %>% 
    select(-std_q, -ACGT, -mean_q)  -> df
}

read_nanoRMS(here("20231111_LWhite_RNA002_v3test.baseFreq.csv")) %>%
  add_column(sample = "RNA002") -> RNA002

read_nanoRMS(here("20231111_LWhite_RNA004_v3test.baseFreq.csv")) %>%
  add_column(sample = "RNA004") -> RNA004

bind_rows(RNA002, RNA004) -> all

```

Put it all in one df and coerce low coverage positions to NA
```{r}
all %>%
  select(`#Ref`, pos, strand, mis, sample, cov) %>%
  dplyr::rename(RNA = `#Ref`) %>%
  pivot_wider(names_from = sample, values_from = c(mis, cov)) %>%
  mutate(diff1 = mis_RNA002 - mis_RNA004) %>%
  group_by(RNA, strand) %>%
  arrange(., pos) %>% # becasue pos isn't numeric correctly?
  filter(strand == "+") %>% # we have some neg strand mapping but v low %
  mutate(mincov1 = pmin(cov_RNA002, cov_RNA004)) %>%
  mutate(adjpos = (pos - 24)) %>% 
  mutate(diff1 = replace(diff1, mincov1 < 29, NA)) -> mismatchdiff

```

Now need to plot this. Look at one tRNA.
```{r}
mismatchdiff %>%
  filter(`RNA`=="Ile-TAT") -> df

# Reshaping the data to long format
long_df <- df %>%
  select(adjpos, mis_RNA002, mis_RNA004) %>%
  pivot_longer(cols = c(mis_RNA002, mis_RNA004), names_to = "RNA_type", values_to = "value") %>%
  filter(!is.na(value))  # Remove NA values

# Plotting
ggplot(long_df, aes(x = adjpos, y = value, color = RNA_type)) +
  geom_rect( # 5´ adapter sequence, median tRNA
    xmin = -25, xmax = 0,
    ymin = -Inf, ymax = Inf,
    fill = "gray", order = -Inf, alpha = .01, inherit.aes = F
  ) +
    geom_rect( # 3´ adapter sequence, median tRNA
    xmin = 76, xmax = 110,
    ymin = -Inf, ymax = Inf,
    fill = "gray", order = -Inf, alpha = .01, inherit.aes = F
  ) +
  geom_rect( # anticodon on median tRNA
    xmin = 34, xmax = 37,
    ymin = -Inf, ymax = Inf,
    fill = "#F0E442", order = -Inf, inherit.aes = F
  ) +
  geom_line(alpha = .8) +
  labs(title = "Mismatch rates across tRNA Ile-TAT",
       x = "Position",
       y = "Value",
       color = "Chemistry") +
  scale_color_manual(values = c("mis_RNA002" = "#000000", "mis_RNA004" = "#CC79A7"),
                     labels = c("mis_RNA002" = "Old", "mis_RNA004" = "New")) +
  theme_cowplot()
  
```
